import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

function AdminAlerts({ onBack }) {
  const [alerts, setAlerts] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    loadAlerts()
  }, [])

  async function loadAlerts() {
    setLoading(true)
    setError('')

    const { data, error } = await supabase
      .from('alerts')
      .select(`
        id,
        route_id,
        shipment_id,
        recipient_id,
        message,
        severity,
        is_read,
        created_at
      `)
      .order('created_at', { ascending: false })

    if (error) {
      console.error('Alerts error:', error)
      setError(error.message)
      setLoading(false)
      return
    }

    setAlerts(data || [])
    setLoading(false)
  }

  function getSeverityClass(severity) {
    if (!severity) return ''

    return `severity-${severity
      .toLowerCase()
      .replace(/\s+/g, '-')}`
  }

  /*
   * Group multiple recipient rows into one alert event.
   *
   * Example:
   *
   * Trader → Route 1 → Shipment 1 → same message
   * Driver → Route 1 → Shipment 1 → same message
   *
   * Admin sees them as one alert.
   */
  const groupedAlerts = Object.values(
    alerts.reduce((groups, alert) => {
      const key = [
        alert.route_id,
        alert.shipment_id,
        alert.message,
        alert.severity,
      ].join('|')

      if (!groups[key]) {
        groups[key] = {
          ...alert,
          recipientIds: [],
          unreadCount: 0,
          readCount: 0,
        }
      }

      if (alert.recipient_id) {
        groups[key].recipientIds.push(
          alert.recipient_id
        )
      }

      if (alert.is_read) {
        groups[key].readCount += 1
      } else {
        groups[key].unreadCount += 1
      }

      return groups
    }, {})
  )

  if (loading) {
    return (
      <div className="dashboard-page">
        <div className="page-content">
          <p>Loading alerts...</p>
        </div>
      </div>
    )
  }

  const unreadCount = alerts.filter(
    (alert) => !alert.is_read
  ).length

  const readCount = alerts.filter(
    (alert) => alert.is_read
  ).length

  return (
    <div className="dashboard-page">
      <div className="page-content">

        {/* Page Header */}
        <div className="page-heading">
          <div>
            <h1>View Alerts</h1>

            <p>
              Monitor system alerts and shipment
              notifications.
            </p>
          </div>

          <button onClick={onBack}>
            ← Back to Dashboard
          </button>
        </div>

        {/* Error Message */}
        {error && (
          <div className="alert alert-error">
            {error}
          </div>
        )}

        {/* Alert Summary */}
        <div className="stats-grid">

          <div className="stat-card">
            <div className="stat-label">
              Alert Events
            </div>

            <div className="stat-value">
              {groupedAlerts.length}
            </div>
          </div>

          <div className="stat-card">
            <div className="stat-label">
              Unread Notifications
            </div>

            <div className="stat-value">
              {unreadCount}
            </div>
          </div>

          <div className="stat-card">
            <div className="stat-label">
              Read Notifications
            </div>

            <div className="stat-value">
              {readCount}
            </div>
          </div>

        </div>

        {/* Alerts Table */}
        <section>

          <div className="section-header">
            <div>
              <h2>System Alerts</h2>

              <p className="section-description">
                Recent alerts generated by the
                logistics system.
              </p>
            </div>

            <button onClick={loadAlerts}>
              ↻ Refresh
            </button>
          </div>

          {groupedAlerts.length === 0 ? (
            <p>No alerts found.</p>
          ) : (
            <div className="table-container">

              <table>

                <thead>
                  <tr>
                    <th>Message</th>
                    <th>Severity</th>
                    <th>Shipment</th>
                    <th>Route</th>
                    <th>Recipients</th>
                    <th>Status</th>
                    <th>Created</th>
                  </tr>
                </thead>

                <tbody>

                  {groupedAlerts.map((alert) => (

                    <tr key={`${alert.route_id}-${alert.shipment_id}-${alert.message}`}>

                      <td>
                        <strong>
                          {alert.message || '-'}
                        </strong>
                      </td>

                      <td>
                        <span
                          className={`severity-badge ${getSeverityClass(
                            alert.severity
                          )}`}
                        >
                          {alert.severity || '-'}
                        </span>
                      </td>

                      <td>
                        {alert.shipment_id || '-'}
                      </td>

                      <td>
                        {alert.route_id || '-'}
                      </td>

                      <td>
                        {alert.recipientIds.length}
                      </td>

                      <td>
                        {alert.unreadCount === 0 ? (
                          <span className="alert-read">
                            Read
                          </span>
                        ) : (
                          <span className="alert-unread">
                            {alert.unreadCount}{' '}
                            Unread
                          </span>
                        )}
                      </td>

                      <td>
                        {alert.created_at
                          ? new Date(
                              alert.created_at
                            ).toLocaleString()
                          : '-'}
                      </td>

                    </tr>

                  ))}

                </tbody>

              </table>

            </div>
          )}

        </section>

      </div>
    </div>
  )
}

export default AdminAlerts